### ISSUE TITLE
Feature Request: Memes Content

### ISSUE THREAD

**Issue by RitheeshBaradwaj** [developers-cosmos/Meme-Generator#1]

**Comment by RitheeshBaradwaj** [comment]
a new file with required content is sent, request for preprocessed strings @Saadia-Hassan

**Comment by Saadia-Hassan** [comment]
Working on it @RitheeshBaradwaj, request @santhoshbandaru, @tharun435, @jaffery0605, @saiprasad-hydraboiny to keep sending memes like before too.
