### ISSUE TITLE
feature needed: preview for image uploading

### ISSUE THREAD

**Issue by RitheeshBaradwaj** [developers-cosmos/Meme-Generator#4]
need a preview while uploading an image from use so that they can crop the portion of the image

**Comment by saiprasad-hydraboiny** [comment]
created a preview for the image using Bootstrap modal and Jcrop and tested on local host

**Comment by RitheeshBaradwaj** [comment]
it is good, we can proceed to the next step. Try to integrate with our website

**Comment by RitheeshBaradwaj** [comment]
I got stuck with the JS file. While Integrating I'm able to save the cropped image, but server is not able to render it. Working on it!
