### ISSUE TITLE
creating REST API for our server

### ISSUE THREAD

**Issue by RitheeshBaradwaj** [developers-cosmos/Meme-Generator#5]
Need a rest API for our flask server , make a sample-test application

**Comment by findtharun** [comment]
Created Basic Flask app API and Tested on Local Host. 
Now We can implement our Algorithm and make API.

**Comment by RitheeshBaradwaj** [comment]
that's cool, now try to work on images, to receive an image from the client do any small operation on it and send back to the client

**Comment by santhoshbandaru** [comment]
Created Flask api  to receive an image from the client and done an operation on it and sent back to the client.

**Comment by RitheeshBaradwaj** [comment]
issue resolved test application is working fine
