### ISSUE TITLE
request for feature: multiple client access

### ISSUE THREAD

**Issue by RitheeshBaradwaj** [developers-cosmos/Meme-Generator#6]
need a test application with server-client architecture to serve multiple clients at the same time

**Comment by santhoshbandaru** [comment]
I have pushed the application with server-client architecture to serve multiple clients at the same time in branch named branch1

**Comment by santhoshbandaru** [comment]
I have created a branch named server-client and in that I pushed files related to application with server-client architecture to serve multiple clients at the same time

**Comment by RitheeshBaradwaj** [comment]
that looks good! now we will try to serve huge requests for our model at same time

**Comment by RitheeshBaradwaj** [comment]
issue resolved got the complete implementation for server-client architecture with multiple access
